### ISSUE TITLE
Installer broken

### ISSUE THREAD

**Issue by bryceac** [voidlinux/void-mklive#82] opened 2016-08-15 01:03 UTC
It looks like I opened up a ticket on the wrong repo and am having some issues with installing images created with this tool.

In order to avoid possibly worrying about dead links, I will just quote what I originally said.

> I have used Void a bit and liked the distribution quite a bit.
> However, when I decided to make a gnome 3 LiveCD, since I needed a touch-friendly Linux system and went about doing test run installation, the installer just exits, with no option asking if I want to reboot like the images on the website do, and when I reboot the machine, I cannot even boot because the install thinks I am running an EFI system, instead of the BIOS system that VirtualBox is set to by default.
> The steps used to create the image are those specified in the mklive script README, with a package setup similar to the following address, which were notes I put down when I made a MATE LiveCD.
> 
> http://wiki.brycecampbell.me/index.php?title=Void_Linux

The MATE LiveCD mentioned was made prior to the online postings of the April images and installed properly, with the expected message asking to reboot.

I also looked at the installer script here and it does not seem to look too different from what it was when I made the MATE LiveCD, though much has changed, like user account creation during install.

Any possibility of this being fixed?

**Comment by Vaelatern** [comment] 2016-08-15 01:37
You don't need a gnome live cd to install a gnome Void instance, you are aware, right?

**Comment by bryceac** [comment] 2016-08-15 02:08
True, but Internet where I am is not as stable or predictable as it used to be, and using gparted, while already installed is far easier than having to convert GB to MB. I also deleted my MATE LiveCD, along with its backup.

I invoke it in a custom shell script that is saved in my home folder as

> sudo ./mklive.should -p '[package list]'

packages are listed in a format similar to what is found in the README.

**Comment by bryceac** [comment] 2016-08-17 03:56
Okay, I created an image today and ran two installation tests from it.

First, I went with a Local install, which is what originally brought up the issue, and things go exactly as I describe. The fresh install with all packages from the LiveCD is not bootable at all and I get no message to be able to reboot.

However, when I do a Network install, everything works as expected, but I want it to install just like the images found on the official site and my old MATE ISO. That iso using MATE was made somewhere around January 2016 and could install successfully via either a local install or network install.

Hopefully this help somewhat.

**Comment by pullmoll** [comment] 2016-08-17 04:05
If you don't use user account creation in void-install, it should behave as it did before.
I didn't try to create a fresh iso, but will do to verify the installer still works (in a VM that is).

**Comment by bryceac** [comment] 2016-08-17 04:17
I will go ahead and give that a try.

**Comment by pullmoll** [comment] 2016-08-17 05:03
First try without void-installer created user account:
+ Created `void-live-x86_64-20160817-xfce.iso` using `build-x86-images.sh`
+ Used `qemu-system-x86_64 -machine accel=kvm -m 8G -smp cpus=12 -vga std -net nic -net user -hda sda.vdi -cdrom void-live-x86_64-20160817-xfce.iso "$@"` with additional parameter `-boot d` to boot the CD.
+ Opened a `xfce-terminal`, ran `sudo -i` and entered `void-installer`
+ Setup without a user account, install from local...
+ Reboot, select `Boot first HD found by BIOS` and it comes up.

So no problem here so far.

**Comment by pullmoll** [comment] 2016-08-17 05:15
It here also works with the default user account created.
So it's not an installer issue, but perhaps your environment.

Do you boot (U)EFI or BIOS? In qemu it's a BIOS boot.

**Comment by bryceac** [comment] 2016-08-17 05:21
It boots with BIOS in Virtualbox. The only time I ever had a VM set to EFI was for an OS X guest.

When I told it to install when I made this issue, I said to not use a graphical boot loader and there appeared a message that search result for Ubuntu came up and it said that message, which said that normal.mod under /grub/1386-pc/ was missing meant that it was configured to boot as EFI, not for BIOS.

**Comment by pullmoll** [comment] 2016-08-17 05:23
Oh, I never tried the (rather new) option `Do not use graphical boot loader` with EFI. This option modifies `/etc/default/grub.conf` and may be incompatible with EFI!?

Perhaps it works if you just don't select that switch?

**Comment by bryceac** [comment] 2016-08-17 05:27
Well, before, I allowed it and I was not getting anything, so I turned it off in the hope that I would get some data and that message is what turned up, instead of the usual choices that crop up when booting without an image.

**Comment by pullmoll** [comment] 2016-08-17 05:33
Ok. In any case it is more probably a machine (or VM) problem, rather than `void-installer` itself.

If you use a raw disk image format in VirtualBox, you can (after installing) also mount that image on your machine and inspect it, i.e. take look at the `/boot/grub` directory and its contents.

I use `losetup -P /dev/loop0 sda.raw` for such cases and can then mount e.g. `/dev/loop0p1` somewhere to look at.

**Comment by pullmoll** [comment] 2016-08-17 05:36
What about trying to **not** add `grub-$arch-efi` to your image?

**Comment by bryceac** [comment] 2016-08-17 05:44
I can certainly remove it and see if that does anything. I only found out that the grub package was necessary via trial and error.

The only confusing thing is that even the images available on the official site still carry it and it does not really affect those.

I will give it a shot tomorrow, since it is getting late, but for right now, I tried without creating a user account and it looks like the issue still persists.

I also noticed in my main void VM tonight that I left out the qemu package mentioned in the README, but that I had it before the other times and things did not change much.

**Comment by bryceac** [comment] 2016-08-17 14:05
I tried removing the grub-$arch-efi package and, like I thought, it did not change anything. the fresh install still stops after scanning locales or sync disks and sends me back to a default prompt upon install, which results in an unbootable system.

I can try using raw disk, but I am guessing that I should install grub-utils too, since the grub boot loader is giving me issues.

**Comment by pullmoll** [comment] 2016-08-17 14:11
Well, since I could not reproduce your problem, I probably can't help you any further.

But to clarify things: you're back to the shell when running `void-installer`? This is not supposed to happen. The installer should exit only if you select exit or reboot installed system.
Otherwise the install may indeed be incomplete.

Did you look at console #8 (Ctrl-Alt-F8) to see if any error message is printed there?

**Comment by bryceac** [comment] 2016-08-17 14:24
After running the Installer, I am sent right back to a blank shell that would allow me to run it again, which only occurs if I select local as the install source, but I can scroll up and see the previous process of scanning for locales or syncing disks.

I can upload the iso somewhere and put a link here, but in case this is may help, I am using a Windows 10 host for Virtualbox and the last time I successfully made an ISO in VirtualBox, I was using OS X.

As far as the console, no I have not tried that, but I will give it a shot.

**Comment by bryceac** [comment] 2016-08-17 23:51
Okay, I could not figure out how to create a RAW disk in VirtualBox, but I did mount my fresh install and found out that the /boot directory was completely empty, unlike the virtual machine where I created the ISO from.

Also, I am trying to upload the image I created, but nothing has occurred yet.

Right now, I created a GZipped tar archive of the boot directory and will try putting that in the new VM.

**Comment by pullmoll** [comment] 2016-08-18 06:15
What is the disk layout you are creating, i.e. partitioning? And what filesystems do you use?
I can only imagine the live image lacks a module for the type of filesystem you chose for `/boot`. That would explain why `/boot` can't be mounted and is empty afterwards.
Why it works with source == net is another question. Perhaps a missing module or mount.* file is not on the live image, but downloaded when you install from the net.

Of course `void-installer` should print an error message rather than falling back to the shell in such a case.

**Comment by bryceac** [comment] 2016-08-18 06:26
I create three partitions in gparted, so that I do not need to do the math of partitioning myself.

Using a MSDOS layout, I set aside, on a 40 GB VDI, 256 MB for /boot, 6 GB for swap, and the rest is set aside for the root partition.

So, it would look like this.

SDA1 - /
SDA2 - /boot
SDA3 - swap

SDA1 uses the ext4 file system.
SDA2 uses ext2 files stem
SDA3 uses Linux swap file system.

SDA1 is made boot able and the rest stays the same.

**Comment by pullmoll** [comment] 2016-08-18 06:57
The usual reason for a separate `/boot` is to make it accessible by some older `BIOS` in case of a huge disk (>2TB) and in that case it has to be the _first_ partition.

And AFAICT it is the `boot` partition which must be marked as bootable, not the `root` partition, so in your case you would have to mark `SDA2` as bootable, not `SDA1`. Or rather swap `SDA1` and `SDA2` sizes and mount points, then still marking `SDA1` as bootable.

How about trying to not initialize the image before and going with a simple *sda1 = ext4 mounted at `/`* , no /boot and no swap space (for a try) and this single partition it as bootable using void-installer's menu instead? I'd be willing to bet this will solve your problems...

**Comment by pullmoll** [comment] 2016-08-18 07:12
I'll try to create a setup like you did and see why `void-installer` fails in that case. It should not, but IMHO it's primarily your setup which is a little odd. :smile_cat:

**Comment by pullmoll** [comment] 2016-08-18 07:39
Ah, I see.. the `Scanning locales...` message is left on the screen because the copying from local stage does not clear the console after hiding the `dialog` window.

However, the system I tried to set up like you did is booting just fine for me, including the partition `sda1` being marked as bootable - which strikes me odd.

Now I can at least add to installer.sh.in clearing the previous output and printing some info that now files will be copied to the destination.

Perhaps the output could go to the console instead of tty8, then a use will see what's going on.. but it's a huge list of files scrolling rapidly through the screen.

I think I have once seen some code which counts the number of output lines of a recursive copy in a dry run, then uses some tool or shell script to print the progress of the actual copy command.
That may be a better solution for void-installer than just showing a message and nothing else for - depending on the machine - minutes.

**Comment by bryceac** [comment] 2016-08-19 00:11
Ok, I probably need to make a new image, though with the installer script not updated things probably will not change.

However, I did get the last ISO I made and ran a test install with only one partition, instead of the usual two or three needed to install Linux, and it was not bootable after install.

When I went to check the /boot directory and it was still empty.

I have tried uploading the image to share here, but things did not work well with the first service, so I am trying to use a different one, and will try to let you have a look.

**Comment by bryceac** [comment] 2016-08-30 04:25
Just thought I would let you guys know that I recently made an image using MATE, instead of GNOME 3, and the installer works fine, just like you guys have seen in your tests, but these problems seem to occur when creating an ISO using GNOME 3 for the LiveCD GUI, so that is possibly the problem.

The link to the image I used no longer works because I deleted the file, but should be reproduceable by just having the mklive script include gnome 3 on the image.

**Comment by pullmoll** [comment] 2016-08-30 19:12
Please before running `void-installer` edit that file and change the line
```
LOG=/dev/tty8
```
to e.g.
```
LOG=>/tmp/install.log
```
That should change all logging to append to the file `/tmp/install.log`

When the failing install is done, save and put the `/tmp/install.log` file somewhere for us to take a look at.

**Comment by bryceac** [comment] 2016-08-31 02:03
I just tried that a few times today and the log file I specify ends up being empty every single time, regardless of permission set and whether I set LOG to "> /tmp/install.log" or /tmp/install.log.

The changes made network impossible to configure and it seems to always failed mounting sda1 or formatting it as ext4.

**Comment by pullmoll** [comment] 2016-08-31 04:11
Then my idea of replacing the single `>` with two `>> for append doesn't work. You could change the value to `LOG=/tmp/install.log` and every occurence of `>$LOG` in the file to `>>$LOG`, which should really work.

**Comment by bryceac** [comment] 2016-09-01 01:23
[install.log contents](https://github.com/voidlinux/void-mklive/files/448608/install.txt)

It took a bit of fiddling to get things working right, but the install finally wrote content to the file and the provided what should be viewable at the provided link.

**Comment by pullmoll** [comment] 2016-09-01 04:55
Ok, so it definitely created the partitions `/ ext4` and `/boot ext2`, mounted them and copied the root fs to the target. But it did **not** execute the `set_bootloader()` code, which can only happen, if the option `BOOTLOADER` is not set.

Are you sure you selected `/dev/sda` in the `BootLoader` menu?

If this was the case, a log line `Running grub-install ... /dev/sda...` would have been written to the log. And after successfully installing grub, then `Running grub-mkconfig -o ...` would have been written.

Both lines are missing which explains why you can't boot the system afterwards.

From looking at the code, I can see no reason but not selecting the boot device in the menu why `set_bootloader()` would do nothing.

**Comment by pullmoll** [comment] 2016-09-01 05:09
Hmm... since it seems to be taking the `DIE()` path here, the commands which could fail are inside the
`if [ "$(get_option SOURCE)" = "local" ]; then` statement are executed.
The `copy_rootfs` was run, and `Removing anon live user from targetdir ...` is **not** logged, so it seems to be dying when `. /etc/default/live.conf` is executed. I doubt the following `rm -f ...` comannds can fail.
What is the contents of `/etc/default/live.conf` on your ISO?

**Comment by pullmoll** [comment] 2016-09-01 05:17
Oh, now I see the line
```
cp: cannot stat '/home/anon/.gvfs': Permission denied
```
which would explain why the `copy_rootfs()` function takes the `DIE()` path!

**Comment by bryceac** [comment] 2016-09-01 05:18
I kind of deleted the ISO, so I will recreate it tomorrow, in order to check its contents, since I get the same results every time anyway.

As for setting the bootloader, yes, I did select /dev/sda during the installation process.

**Comment by pullmoll** [comment] 2016-09-01 05:19
It looks like this gnome vfs special directory is killing the copy command, or rather make it fail, which is why `copy_rootfs()` calls `DIE 1`.

**Comment by pullmoll** [comment] 2016-09-01 05:25
Instead of the copy command, we could try with a `tar pipe`. I used it in PR #83 to count the number of files to copy before actually copying them.

I will create a gnome based installer ISO and see if that works better than the failing `cp -axvnu / $TARGETDIR` command.

**Comment by pullmoll** [comment] 2016-09-01 22:17
Ok, I now created a live ISO according to your specs (packages) and using my PR #83, which replaces the failing `cp` with a `tar pipe` and a progress info box. This, besides other improvements, solves the error which makes `copy_rootfs()` fail in the current installer.

This ISO is **not** based on the official current repository, but on a `gcc-5.4.0` bootstrapped repository available at http://repo.voidlinux.de/current .

There I'm currently rebuilding all packages from scratch, adding patches for packages which need them for the coming move from `gcc-4.9.4` to `gcc-5.4.0`, or perhaps `gcc-5.2.0` in a first step.

This issue seems like a good test case, since many widely used packages are included.

You can download the ISO (soon) at http://repo.voidlinux.de/live and give it a try. It worked for me in `qemu` and `void-installer` created a bootable disk with one ext4 partition mounted at `/`.

**Comment by bryceac** [comment] 2016-09-02 00:20
I just tried the image, and although it used MATE instead of GNOME, like I was trying to do, it worked out great and seeing a progress bar is definitely more reassuring than the absence of anything being shown in the terminal.

I will try waiting for the changes you made and such before trying to test things out for myself.

**Comment by pullmoll** [comment] 2016-09-02 02:23
... but there was `mate + mate-extras` on your page http://wiki.brycecampbell.me/index.php?title=Void_Linux :smile: 

I'll build an ISO with gnome and put it up.

**Comment by bryceac** [comment] 2016-09-02 02:33
I know. I had MATE and MATE extras there. that was the last time I was able to get a decent setup, and I am grateful that you kept to it.

In my opening post on the issue, I my package setup this time was similar, not the exact same, to that package list.

The GNOME one I had did not feature claws and used GDM instead of LXDM, since I no longer got the same issues I did when I first made my LiveCD and tried using LightDM, but other than that, the package list is still the same.

**Comment by pullmoll** [comment] 2016-09-04 01:58
Hum.. I probably installed too many gnome packages on the ISO or missed something. I get an error when the anon user autlogin tries to start up gnome.

Can you give a list of packages you added to `-p ...`?

**Comment by bryceac** [comment] 2016-09-05 13:52
Packages are as follows:

gimp
inkscape
scribus
gparted (helps with partitioning process)
libreoffice
k3B
vlc
dbus
dialog (needed to install)
cups (needed for printing)
foomatic-db
foomatic-db-engine
hplip (HP printer drivers)
avahi (needed to easily see network shares)
avahi-utilities
gvfs (and add ons, like gvfs-afp, gvfs-smb, gvfs-mtp) (needed to browse network shares)
transmission-gtk
xorg (needed to get GUI working)
GDM 
system-config-printer
hfsprogs (read Mac formatted disks)
ntfs-3g (read NTFS formatted disks)
exfat-utils (utilities for exFAT support)
nano (simple text editor for cli use)
zsh (shell with tab completion)
chromium
libdvdcss (needed for DVD support)
grub + grub-$arch-efi (needed to have installation work (replace $arch with i386 for 32-bit and x86_64 for 64-bit)

**Comment by pullmoll** [comment] 2016-09-05 14:56
Ok, `GDM` is `gdm` and `avahi-utilities` is `avahi-utils`. I will create a gnome ISO from official packages, because I'm currently rebuilding the gcc-5.4.0 stuff, test it and upload it afterwards.

**Comment by bryceac** [comment] 2016-09-06 01:17
I know case matters. I posted that using a device that seems to have the autocorrect annoyance.

Anyway, I am downloading it now, but GDM is quite difficult to check, because things have change dramatically from the 2.x days.

**Comment by pullmoll** [comment] 2016-09-10 09:17
#83 is merged and fixes the bug.

**Closed by pullmoll** 2016-09-10 09:17 UTC
